General API for NPC support
PikaMug/Quests pull request #2314
Opened 2024-12-18 18:54 UTC by HSGamer

This introduces a general NPC API so that It's easier to add support for future NPC plugins instead of painstakingly checking all NPC code anytime we add support for a new NPC plugin.

This is marked as a breaking change because it would break any addons that gets NPC plugin instances from `BukkitDependencies` (e.g. https://github.com/PikaMug/GPS-Quests).

This is currently marked as a draft as it's not thoroughly tested and I want to resolve some Citizens-specific code. A development build will be available when the PR is completed.

2024-12-19 11:35 UTC, HSGamer commented
Dev build for those who are interested:

[Quests-5.zip](https://github.com/user-attachments/files/18197063/Quests-5.zip)

2024-12-19 16:44 UTC, PikaMug commented
Thank you for submitting this. I've noticed desire in the community for FancyNpcs support. My thoughts were focused on creating a shadeable library for this (similar to [Unite](https://github.com/PikaMug/Unite)), but I'm not opposed to direct integration. Might be a little soon to remove legacy ZNPCsPlus, as there hasn't been much time for users to adapt (only released 6 days ago), but that's not a deal breaker. Will likely be taking a second look at this PR after the holidays. 🎁

2025-01-02 22:10 UTC, PikaMug requested changes
Thanks for your patience. According to [bStats](https://bstats.org/plugin/bukkit/ZNPCsPlus/18244), between 11% and 12% of reporting users are still running a 1.0.x version of ZNPCsPlus. Although I don't know how many also have Quests installed, that still feels significant. If you would restore that support, I'd be happy to merge this request.

2025-01-03 10:26 UTC, HSGamer commented
I added the legacy znpcsplus back

2025-01-03 10:29 UTC, HSGamer commented
I'm planning to make a similar unified library for NPC as one of my [ProjectUnified](https://github.com/ProjectUnified) projects.
So, I may make another PR for that in the future when I finish making one.

2025-01-05 19:31 UTC, PikaMug approved these changes

2025-01-05 19:34 UTC, merged

2025-01-05 20:21 UTC, PikaMug commented
Unfortunately, I've had to revert this as the commit cannot be compiled with Java 8. It seems the minimum for FancyNpcs is Java 17. This could probably be worked around using an external library as previously discussed. Should the Quests project increase its minimum Java version, I'll revisit this PR. My apologies for any inconvenience caused. The zipped version linked above is available for anyone in need of FancyNpcs support.

2025-01-06 03:47 UTC, HSGamer commented
Continue in #2320